# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af98f0179856033e7e49f61de660e8bc1cea3ce874901a13ac641c81aff32dde0074e0233dea310208dd310cc2e1e909d5106519f48e8dda544d1a8b6ebb2d60

test:
  secret_key_base: 8eef9150cb3bc98d6075f9931f990f382dea974fe94c007710a7d27b36066b05f7aa61a6a02fc5d3cf3719a24680b060384bd2e2d2bd41d4b4ba0d8e224acfa4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
